"""Summarise the sampling sensitivity check against the greedy sweep.

Reads ``results_sampling/<run>/<model>/step*.json`` (one run directory per seed)
and the greedy logs in ``results/<model>/``, and writes a LaTeX table plus macros:

    python scripts/sampling_summary.py --tables-dir report/tables
"""

from __future__ import annotations

import argparse
import json
import statistics
from pathlib import Path

MODEL_DIR = "dhgottesman__LMEnt-170M-6E"


def load_metrics(path: Path) -> dict:
    d = json.loads(path.read_text())
    m = d["metrics"]
    ans, un = m["answerable"], m["unanswerable"]
    return {
        "step": int(d["config"]["step"]),
        "temperature": d["config"].get("temperature", 0.0),
        "hr": un["hallucination_rate"],
        "ehr": un["entity_hallucination_rate"],
        "ar_un": un["abstention_rate"],
        "ar_ans": ans["abstention_rate"],
        "sel": un["abstention_rate"] - ans["abstention_rate"],
        "sub": ans["substring_match"],
        "conf_delta": m["paired_confidence"]["delta"],
        "conf_p": m["paired_confidence"]["p_value_permutation"],
    }


def mean_sd(vals: list[float]) -> tuple[float, float]:
    return statistics.fmean(vals), (statistics.stdev(vals) if len(vals) > 1 else 0.0)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--sampling-dir", type=Path, default=Path("results_sampling"))
    ap.add_argument("--greedy-dir", type=Path, default=Path("results"))
    ap.add_argument("--tables-dir", type=Path, default=Path("report/tables"))
    args = ap.parse_args()

    runs = sorted(p for p in args.sampling_dir.iterdir() if (p / MODEL_DIR).is_dir())
    per_step: dict[int, list[dict]] = {}
    temperature = None
    for run in runs:
        for f in sorted((run / MODEL_DIR).glob("step*.json")):
            r = load_metrics(f)
            temperature = r["temperature"]
            per_step.setdefault(r["step"], []).append(r)
    steps = sorted(s for s, rs in per_step.items() if len(rs) == len(runs))
    greedy = {s: load_metrics(args.greedy_dir / MODEL_DIR / f"step{s}.json") for s in steps}

    def fmt(vals: list[float]) -> str:
        m, sd = mean_sd(vals)
        return f"{m:.3f} $\\pm$ {sd:.3f}"

    lines = [
        "% Auto-generated by scripts/sampling_summary.py -- do not edit by hand.",
        "\\begin{tabular}{r rr rr rr}",
        "\\toprule",
        "& \\multicolumn{2}{c}{HR} & \\multicolumn{2}{c}{AR (answerable)} & \\multicolumn{2}{c}{Selectivity} \\\\",
        "\\cmidrule(lr){2-3} \\cmidrule(lr){4-5} \\cmidrule(lr){6-7}",
        "Step & Greedy & Sampled & Greedy & Sampled & Greedy & Sampled \\\\",
        "\\midrule",
    ]
    for s in steps:
        g, rs = greedy[s], per_step[s]
        lines.append(
            f"{s:,} & {g['hr']:.3f} & {fmt([r['hr'] for r in rs])} & "
            f"{g['ar_ans']:.3f} & {fmt([r['ar_ans'] for r in rs])} & "
            f"{g['sel']:.3f} & {fmt([r['sel'] for r in rs])} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}", ""]
    args.tables_dir.mkdir(parents=True, exist_ok=True)
    (args.tables_dir / "sampling_results.tex").write_text("\n".join(lines))

    hr_gap = statistics.fmean(abs(statistics.fmean(r["hr"] for r in per_step[s]) - greedy[s]["hr"]) for s in steps)
    sel_max = max((statistics.fmean(r["sel"] for r in per_step[s]), s) for s in steps)
    sd_max = max(mean_sd([r["hr"] for r in per_step[s]])[1] for s in steps)
    last = steps[-1]
    macros = {
        "SampTemperature": f"{temperature:g}",
        "SampNumSeeds": str(len(runs)),
        "SampNumCkpts": str(len(steps)),
        "SampHRGapMean": f"{hr_gap:.3f}",
        "SampHRSDMax": f"{sd_max:.3f}",
        "SampSelMax": f"{sel_max[0]:.3f}",
        "SampSelMaxStep": f"{sel_max[1]:,}",
        "SampConfDeltaLast": f"{statistics.fmean(r['conf_delta'] for r in per_step[last]):.3f}",
    }
    (args.tables_dir / "sampling_macros.tex").write_text(
        "% Auto-generated by scripts/sampling_summary.py -- do not edit by hand.\n"
        + "".join(f"\\newcommand{{\\res{k}}}{{{v}}}\n" for k, v in macros.items())
    )
    print(json.dumps({"steps": steps, "seeds": len(runs), **macros}, indent=2))
    for s in steps:
        print(s, {k: round(statistics.fmean(r[k] for r in per_step[s]), 3) for k in ("hr", "ehr", "ar_un", "ar_ans", "sel", "sub", "conf_delta")},
              "greedy", {k: round(greedy[s][k], 3) for k in ("hr", "ehr", "ar_ans", "sel")})
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
